// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxvyneWGxnNHHC_40BAsol018T44e2T_o',
    appId: '1:672060625313:web:282bb46d18c764877cfbe0',
    messagingSenderId: '672060625313',
    projectId: 'zero-hunger-af418',
    authDomain: 'zero-hunger-af418.firebaseapp.com',
    databaseURL: 'https://zero-hunger-af418-default-rtdb.firebaseio.com',
    storageBucket: 'zero-hunger-af418.firebasestorage.app',
    measurementId: 'G-PXL4BLFMWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFVbqqnYZCuk5BJfFBsZIqyyT5gXdu0dA',
    appId: '1:672060625313:android:cf4e4c14ffcddd537cfbe0',
    messagingSenderId: '672060625313',
    projectId: 'zero-hunger-af418',
    databaseURL: 'https://zero-hunger-af418-default-rtdb.firebaseio.com',
    storageBucket: 'zero-hunger-af418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8TUUJzDAj_-auHCj_1fDvXx3h-J3gmXM',
    appId: '1:672060625313:ios:979a6874e1e56dd87cfbe0',
    messagingSenderId: '672060625313',
    projectId: 'zero-hunger-af418',
    databaseURL: 'https://zero-hunger-af418-default-rtdb.firebaseio.com',
    storageBucket: 'zero-hunger-af418.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8TUUJzDAj_-auHCj_1fDvXx3h-J3gmXM',
    appId: '1:672060625313:ios:979a6874e1e56dd87cfbe0',
    messagingSenderId: '672060625313',
    projectId: 'zero-hunger-af418',
    databaseURL: 'https://zero-hunger-af418-default-rtdb.firebaseio.com',
    storageBucket: 'zero-hunger-af418.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxvyneWGxnNHHC_40BAsol018T44e2T_o',
    appId: '1:672060625313:web:7ea5c5f091485ee97cfbe0',
    messagingSenderId: '672060625313',
    projectId: 'zero-hunger-af418',
    authDomain: 'zero-hunger-af418.firebaseapp.com',
    databaseURL: 'https://zero-hunger-af418-default-rtdb.firebaseio.com',
    storageBucket: 'zero-hunger-af418.firebasestorage.app',
    measurementId: 'G-CM957VHP8H',
  );
}
